server:
  port: 8190
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sandeepmknair/spring-cloud-config-store/
          search-paths:
           - '*service'
